version: '3'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  pixel-service:
    build:
      context: ./PixelService
      dockerfile: Dockerfile
    ports:
      - "5254:8080"
    environment:
      KAFKA__BOOTSTRAPSERVER: kafka:9092
    depends_on:
      - kafka

  storage-service:
    build:
      context: ./StorageService
      dockerfile: Dockerfile
    ports:
      - "5255:8080"
    environment:
      KAFKA__BOOTSTRAPSERVER: kafka:9092
    depends_on:
      - kafka
